---
abstract: 'Object class for storing and retrieving a lexicon in a tree of affixes'
author:
  - 'S. Randall Sawyer <srandalls@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-Lexicon
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 0.01
